/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      'lh3.googleusercontent.com',
      'media-cldnry.s-nbcnews.com',
      'static.foxnews.com',
      'media.cnn.com',
      'cdn.cnn.com',
      'a57.foxnews.com',
      'www.washingtonpost.com',
      'images.wsj.net',
      'www.nytimes.com',
      'static01.nyt.com',
      'nypost.com',
      'assets.bwbx.io',
      'ichef.bbci.co.uk',
      'i.guim.co.uk',
      'images.unsplash.com',
      'img.huffingtonpost.com',
      'cbsnews.com',
      'cbsnews1.cbsistatic.com',
      'cbsnews2.cbsistatic.com',
      'abcnews.go.com',
      's.abcnews.com',
      'media.npr.org',
      'media.breitbart.com',
      'thehill.com',
      'img.theepochtimes.com',
      'www.aljazeera.com',
      'media.newyorker.com',
      'cdn.vox-cdn.com',
      'media.wired.com',
      'media.vanityfair.com',
      'media.newyorker.com',
      'media.theatlantic.com',
      'www.rollingstone.com',
      'img.buzzfeed.com',
      'media.salon.com',
      'www.dailymail.co.uk',
      'i.dailymail.co.uk',
      'i.kinja-img.com',
      'assets.bwbx.io',
      'www.reuters.com',
      'www.ft.com',
      'www.economist.com',
      'www.bloomberg.com',
      'www.businessinsider.com',
      'www.forbes.com',
      'www.cnbc.com',
      'www.marketwatch.com',
      'www.barrons.com',
      'www.ft.com',
      'www.ft.com',
    ],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  },
};

module.exports = nextConfig;
